spring:
  application:
    name: SpringAI-demo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:14b
        options:
          temperature: 0.7
logging:
  level:
    org.springframework.ai: debug
    com.liu.springai_demo: debug